### ISSUE TITLE
Change projection and central logitude

### ISSUE THREAD

**Issue by davidmnielsen** [gauteh/ibcao_py#3]
Hello, is there a way to change the projection and cental longitude in `f = i.template ()`? How can I modify this outcome? I would like to use something like Cartopy's `proj=ccrs.Mercator(central_longitude=120)`. This would allow me to focus on the Laptev Sea, for example, using the appropriate `set_extent` parameters.

My objective is to have this region in this projection, but displaying IBCAO data: 
![image](https://user-images.githubusercontent.com/39162069/68680163-7ae4c100-0561-11ea-889b-ad23c4adc0f8.png)

The code for the above figure:
```python
import matplotlib.pyplot as plt
from matplotlib.transforms import offset_copy
import cartopy.crs as ccrs
import cartopy.io.img_tiles as cimgt


def main():
    stamen_terrain = cimgt.Stamen('terrain-background')
    stamen_waterco = cimgt.Stamen('watercolor')
    fig = plt.figure(figsize=(10,10))
    ax = fig.add_subplot(1, 1, 1, projection=stamen_terrain.crs)
    ax.set_extent([126.5, 131.5, 71, 72.5], crs=ccrs.Geodetic())
    ax.add_image(stamen_terrain, 8)
    geodetic_transform = ccrs.Geodetic()._as_mpl_transform(ax)
    text_transform = offset_copy(geodetic_transform, units='dots', x=-25)
    plt.show()
if __name__ == '__main__':
    main()

```

I get funny results if I just adjust the extent, following the documentation.:
```python
f = i.template ()
f.set_size_inches (10, 10)
f.gca().set_extent ((126.5, 131.5, 71, 72.5))
```

![image](https://user-images.githubusercontent.com/39162069/68680428-ed55a100-0561-11ea-8442-9ee86a1aa46d.png)

**Comment by gauteh** [comment]
Hi, sorry for the delayed response. Starting from the template() function and setting an extent this might be suitable:

```
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
from ibcao import IBCAO
import numpy as np

div = 1

i = IBCAO ()
f = plt.figure ()
ax = plt.axes (projection = i.projection)
ax.set_xlim (*i.xlim)
ax.set_ylim (*i.ylim)

ax.coastlines ('10m')
ax.gridlines (crs = i.g, ylocs = np.arange (60, 90, 5))

# plot every 'div' data point
(cmap, norm) = i.Colormap ()
cm = ax.pcolorfast (i.x[::div], i.y[::div], i.z[::div, ::div], cmap = cmap, norm = norm)
cb = plt.colorbar (cm)
cb.set_label ('Depth [m]')

ax.set_extent([126.5, 131.5, 71, 72.5], crs=ccrs.Geodetic())

plt.title ('The International Bathymetric Chart of the Arctic Ocean')
plt.show()
```

if you change the projection of the map the plotting will become expansive. But it might be possible when using a lower resolution (`div` in the snippet above) or for a limited extent.

![extent](https://user-images.githubusercontent.com/56827/70236669-b1c78480-1765-11ea-9c3b-85c594edd4fd.png)

Note: seems like the colorscale/norm might be off by one..?

**Comment by gauteh** [comment]
Here is an example using Mercator:

```
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
from ibcao import IBCAO
import numpy as np

div = 100

i = IBCAO ()
f = plt.figure ()
ax = plt.axes (projection = ccrs.Mercator())
ax.coastlines ('10m')
ax.gridlines (crs = i.g, ylocs = np.arange (60, 90, 5))

# plot every 'div' data point
(cmap, norm) = i.Colormap ()

cm = ax.imshow(i.z[::div,::div], extent=i.imextent, cmap=cmap, norm=norm, transform=i.ups)
cb = plt.colorbar (cm)
cb.set_label ('Depth [m]')

#ax.set_extent([126.5, 131.5, 71, 72.5], crs=ccrs.Geodetic())

plt.title ('The International Bathymetric Chart of the Arctic Ocean')

plt.show()
```

Note that I had to use a large `div` to plot this in reasonable time. You might be able to plot it with a limited extent and lesser div. Otherwise, you might have better luck extracting a box from `i.z` and adjusting the `imextent`. Note that `imextent` was just added in the latest commit, but it can be constructed from: `[*i.xlim, *.ylim]`.

![mercator](https://user-images.githubusercontent.com/56827/70236691-b9872900-1765-11ea-8f04-d039a6e9bbd8.png)
